version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.3
    commands:
      - echo Installing Terraform
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform
      - terraform init

  build:
    commands:
      - echo Planning Terraform Deployment
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform Deployment
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: yes